[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = "mathTools"
version = "2023.4.7.6"
packages = ["find:"]
where = "src"
install_requires = ["ipython", "black", "pandas", "pytest", "mypy"]
tests_require = ["unittest"]
test_suite = "tests"