[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = "mathTools"
version = "2023.4.7.5"
packages = ["mathTools"]
package_dir = {"": "src"}
install_requires = ["ipython", "black", "pandas", "pytest", "mypy"]
tests_require = ["unittest"]
test_suite = "tests"