name: Pytest and Black
    
on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          pip install git+https://github.com/ocjr/python-gld-practice.git
        elif [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
          pip install git+https://github.com/ocjr/python-gld-practice.git@${{ github.ref }}
        else
          echo "Unsupported branch: ${{ github.ref }}"
          exit 1
        fi    
    - name: Run pytest
      run: pytest
    - name: Run black
      run: black .
    - name: Run mypy
      run: mypy --ignore-missing-imports src/
